logging:
  pattern:
    console: "%white(%d{HH:mm:ss.SSS}) %clr(%5p) [%clr(%20t){blue}] %clr(%40logger{39}){cyan} %clr(:){green} %m%n%wEx"
  level:
    org.nth: debug

info:
  app:
    name: @project.name@
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@

server:
  port: 9888

management: # Management configuration
  endpoint:
    logfile:
      external-file: ${logging.file.name:}.log
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    java:
      enabled: true
  httpexchanges:
    recording:
      include: REQUEST_HEADERS, RESPONSE_HEADERS, COOKIE_HEADERS, AUTHORIZATION_HEADER, PRINCIPAL, REMOTE_ADDRESS, SESSION_ID, TIME_TAKEN

spring:
  application:
    name: ${info.app.artifactId}
    instance-id: ${spring.application.name}-01
  main:
    banner-mode: log

eureka:
  instance:
    instance-id: ${spring.application.instance-id:${server.port}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 30
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
      name: ${spring.application.name}
      instance-id: ${spring.application.instance-id}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka/ # URL to Eureka at msg-gw-discovery 
    healthcheck:
      enabled: true